### ISSUE TITLE
Access to route params when matching routes

### ISSUE THREAD

**Issue by markdalgleish** [ReactTraining/react-router-addons-routes#4]
When calling `matchRoutesToLocation`, we currently only get access to the matched routes, but don't have access to the `params` object, which is pretty critical for data fetching.

Currently, `matchRoutesToLocation` returns an array of routes, but perhaps instead it should return an object containing matched routes and params? e.g. `{ matchedRoutes: [ ... ], params: { ... } }`

I'd be happy to implement this feature, but figured I should check in and get some feedback before rushing ahead on it.

**Comment by mjackson** [comment]
Indeed, you'll need access to the params. In router v2 this is what we called a "match". I'd be happy to see a PR that does something like what you describe, @markdalgleish.

**Comment by markdalgleish** [comment]
Started working on this, but stumbled over an existing issue which I've opened a PR for (https://github.com/ReactTraining/react-router-addons-routes/pull/5). Once this issue is fixed, I'll move onto the param handling logic.

**Comment by ctrlplusb** [comment]
@mjackson @ryanflorence - sorry, know you guys are like uber busy people, but do you think there is any chance of adding @markdalgleish as a contributor to keep things rolling?  I am eagerly awaiting his changes to support my SSR needs with RR4.

Sorry, I know this sounds pushy, but it's your fault for creating such an awesome library.  I am salivating.

**Comment by ryanflorence** [comment]
He's added now and can also ship releases to npm :)

**Comment by ctrlplusb** [comment]
Legend. Thanks!

**Comment by markdalgleish** [comment]
@ctrlplusb now available in v0.0.2 :smile:
