### ISSUE TITLE
An alternative approach to prefetching of data

### ISSUE THREAD

**Issue by ctrlplusb** [ReactTraining/react-router-addons-routes#9]
Whilst having the centralized routing config is useful in doing matches to determine the component pool for a route and then do things like data prefetching, I feel like using this centralized approach is one step backwards from the advancements that RR4 put on the table.  I feel like we get pulled away from the "easy to reason about" nested component structure that RR4 provides us with it's `Match`, `Miss` et al. components.  

Literally the only reason I am choosing to go for a centralized routing configuration is so that I can do some data prefetching on the server. Therefore, I gave this a bit more thought, and came up with an alternative approach.

Instead of having a centralized `routes` configuration, create a centralized `dataRoutes` configuration, similar to:

```js
const dataRoutes = [{
   pattern: '/topics',
   prefetch: (props) => promiseReturningAction(),
   defer: (props) => promiseReturningAction(),
}]
```

Using this approach I need only define route matches for the points that I expect to have some sort of data requirement.  The `dataRoutes` isn't used for any rendering within the application, it simply serves as a source that I can pattern match against to determine what actions I should be executing prior to rendering my application.

I could then use it on the server like so:

```js
const result = matchRoutesToLocation(dataRoutes, window.location);
const { matchedRoutes, params } = result;

Promise.all(
  matchedRoutes
    .filter(dataRoute => dataRoute.prefetch)
    .map(dataRoute => dataRoute.prefetch(params))
).then((data) => {
  if (data) {
    // Do something with the data
  }

  const html = renderToString(
    <AppContainer>
      <ServerRouter>
        <div>
          <Match exactly pattern="/" component={Home} />
          <Match pattern="/about" component={About} />
          <Match pattern="/topics" component={Topics}
        </div
      </ServerRouter>
    </AppContainer>
  );
});
```

Within my app I then just use the standard React Router 4 API's etc, knowing that all the data needed I anticipated to be needed will have been loaded already.

There are a couple of issues with this approach of course:

  - You aren't collocating your data needs with your Components, which may be confusing I guess, but I haven't actually tried this in anger so I have no idea.
  - You need the data hooks (e.g. `prefetch`) to result in the data being bound against a centralized store (e.g. Redux) as the data routes configuration knows nothing about exactly what components will be rendered so it can't pass the data down to them directly.

I feel like it's a trade off of sorts, but I like that I can just use the standard RR4 API within my app components thereafter.

Thoughts?

**Comment by ryanflorence** [comment]
Yeah, this is an approach I've expected, would be perfect for apps without a bunch of routes.
